cookie:
  expiry_days: 30
  key: asldfjoi2jiosu2983ujeijaf9sdu3uroiaejf;kl
  name: language_learning_app_cookie
credentials:
  usernames:
    robin:
      email: de0293urjaslkdjfs@gmail.com
      first_name: Dene
      last_name: Me
      password: $2b$12$KIXQ5T1b/6Oj3eL5Z5N9bu9WV1mZWG.b8XcB8kP1K/s6sG.XxYmKG
    rvdb:
      email: rvdb7345@gmail.com
      first_name: Robin
      last_name: Berg
      logged_in: true
      password: $2b$12$hZfw4kUkOFOZQ4bsOu5L7eD0C2xA5uB9Tfd3qjW0nI1p93AXUzc9u
      password_hint: '234'
      roles: null
preauthorized:
  emails:
  - rvdb7345@gmail.com
